// Mocks generated by Mockito 5.4.6 from annotations
// in nutrisync/test/integration/voice_first_ai_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:nutrisync/models/user_model.dart' as _i2;
import 'package:nutrisync/services/user_profile_service.dart' as _i8;
import 'package:nutrisync/voice/conversation_context_manager.dart' as _i7;
import 'package:nutrisync/voice/voice_interface.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirestoreResult_0<T> extends _i1.SmartFake
    implements _i2.FirestoreResult<T> {
  _FakeFirestoreResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [VoiceInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoiceInterface extends _i1.Mock implements _i3.VoiceInterface {
  MockVoiceInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isListening => (super.noSuchMethod(
        Invocation.getter(#isListening),
        returnValue: false,
      ) as bool);

  @override
  bool get isPlaying => (super.noSuchMethod(
        Invocation.getter(#isPlaying),
        returnValue: false,
      ) as bool);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<bool> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<String> processVoiceInput(_i5.Uint8List? audioData) =>
      (super.noSuchMethod(
        Invocation.method(
          #processVoiceInput,
          [audioData],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #processVoiceInput,
            [audioData],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<_i5.Uint8List> recordAudio({int? durationSeconds = 5}) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordAudio,
          [],
          {#durationSeconds: durationSeconds},
        ),
        returnValue: _i4.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
      ) as _i4.Future<_i5.Uint8List>);

  @override
  _i4.Future<String> listenForVoiceInput({int? timeoutSeconds = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #listenForVoiceInput,
          [],
          {#timeoutSeconds: timeoutSeconds},
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #listenForVoiceInput,
            [],
            {#timeoutSeconds: timeoutSeconds},
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<_i5.Uint8List> generateVoiceResponse(String? text) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateVoiceResponse,
          [text],
        ),
        returnValue: _i4.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
      ) as _i4.Future<_i5.Uint8List>);

  @override
  _i4.Future<void> playAudio(_i5.Uint8List? audioBytes) => (super.noSuchMethod(
        Invocation.method(
          #playAudio,
          [audioBytes],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> stopAudio() => (super.noSuchMethod(
        Invocation.method(
          #stopAudio,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<_i3.VoiceInteraction> startConversation({
    String? userId,
    Map<String, dynamic>? initialContext,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startConversation,
          [],
          {
            #userId: userId,
            #initialContext: initialContext,
          },
        ),
        returnValue: _i4.Stream<_i3.VoiceInteraction>.empty(),
      ) as _i4.Stream<_i3.VoiceInteraction>);

  @override
  void handleInterruption({String? reason}) => super.noSuchMethod(
        Invocation.method(
          #handleInterruption,
          [],
          {#reason: reason},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<String> resumeConversation() => (super.noSuchMethod(
        Invocation.method(
          #resumeConversation,
          [],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #resumeConversation,
            [],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> generateContextualResponse(
    String? userInput,
    String? baseResponse,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateContextualResponse,
          [
            userInput,
            baseResponse,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #generateContextualResponse,
            [
              userInput,
              baseResponse,
            ],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  void addMealContext(Map<String, dynamic>? mealData) => super.noSuchMethod(
        Invocation.method(
          #addMealContext,
          [mealData],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateUserPreferences(Map<String, dynamic>? preferences) =>
      super.noSuchMethod(
        Invocation.method(
          #updateUserPreferences,
          [preferences],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i7.ConversationTurn> getConversationHistory() => (super.noSuchMethod(
        Invocation.method(
          #getConversationHistory,
          [],
        ),
        returnValue: <_i7.ConversationTurn>[],
      ) as List<_i7.ConversationTurn>);

  @override
  void endConversation() => super.noSuchMethod(
        Invocation.method(
          #endConversation,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<bool> testElevenLabsConnection() => (super.noSuchMethod(
        Invocation.method(
          #testElevenLabsConnection,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAvailableVoices() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableVoices,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UserProfileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileService extends _i1.Mock
    implements _i8.UserProfileService {
  MockUserProfileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.FirestoreResult<_i2.UserModel>> createProfile({
    required String? uid,
    required String? name,
    required String? email,
    List<String>? dietaryNeeds,
    List<String>? healthGoals,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProfile,
          [],
          {
            #uid: uid,
            #name: name,
            #email: email,
            #dietaryNeeds: dietaryNeeds,
            #healthGoals: healthGoals,
          },
        ),
        returnValue: _i4.Future<_i2.FirestoreResult<_i2.UserModel>>.value(
            _FakeFirestoreResult_0<_i2.UserModel>(
          this,
          Invocation.method(
            #createProfile,
            [],
            {
              #uid: uid,
              #name: name,
              #email: email,
              #dietaryNeeds: dietaryNeeds,
              #healthGoals: healthGoals,
            },
          ),
        )),
      ) as _i4.Future<_i2.FirestoreResult<_i2.UserModel>>);

  @override
  _i4.Future<_i2.FirestoreResult<_i2.UserModel>> updateProfile({
    required String? uid,
    String? name,
    String? email,
    int? age,
    String? gender,
    double? height,
    double? weight,
    String? activityLevel,
    List<String>? dietaryNeeds,
    List<String>? healthGoals,
    List<String>? medicalConditions,
    List<String>? allergies,
    List<String>? foodDislikes,
    String? preferredLanguage,
    Map<String, dynamic>? culturalPreferences,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #uid: uid,
            #name: name,
            #email: email,
            #age: age,
            #gender: gender,
            #height: height,
            #weight: weight,
            #activityLevel: activityLevel,
            #dietaryNeeds: dietaryNeeds,
            #healthGoals: healthGoals,
            #medicalConditions: medicalConditions,
            #allergies: allergies,
            #foodDislikes: foodDislikes,
            #preferredLanguage: preferredLanguage,
            #culturalPreferences: culturalPreferences,
          },
        ),
        returnValue: _i4.Future<_i2.FirestoreResult<_i2.UserModel>>.value(
            _FakeFirestoreResult_0<_i2.UserModel>(
          this,
          Invocation.method(
            #updateProfile,
            [],
            {
              #uid: uid,
              #name: name,
              #email: email,
              #age: age,
              #gender: gender,
              #height: height,
              #weight: weight,
              #activityLevel: activityLevel,
              #dietaryNeeds: dietaryNeeds,
              #healthGoals: healthGoals,
              #medicalConditions: medicalConditions,
              #allergies: allergies,
              #foodDislikes: foodDislikes,
              #preferredLanguage: preferredLanguage,
              #culturalPreferences: culturalPreferences,
            },
          ),
        )),
      ) as _i4.Future<_i2.FirestoreResult<_i2.UserModel>>);

  @override
  _i4.Future<_i2.FirestoreResult<_i2.UserModel>> getProfile(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [uid],
        ),
        returnValue: _i4.Future<_i2.FirestoreResult<_i2.UserModel>>.value(
            _FakeFirestoreResult_0<_i2.UserModel>(
          this,
          Invocation.method(
            #getProfile,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.FirestoreResult<_i2.UserModel>>);

  @override
  _i4.Future<_i2.FirestoreResult<void>> addMedicalCondition(
    String? uid,
    String? condition,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMedicalCondition,
          [
            uid,
            condition,
          ],
        ),
        returnValue: _i4.Future<_i2.FirestoreResult<void>>.value(
            _FakeFirestoreResult_0<void>(
          this,
          Invocation.method(
            #addMedicalCondition,
            [
              uid,
              condition,
            ],
          ),
        )),
      ) as _i4.Future<_i2.FirestoreResult<void>>);

  @override
  _i4.Future<_i2.FirestoreResult<void>> removeMedicalCondition(
    String? uid,
    String? condition,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMedicalCondition,
          [
            uid,
            condition,
          ],
        ),
        returnValue: _i4.Future<_i2.FirestoreResult<void>>.value(
            _FakeFirestoreResult_0<void>(
          this,
          Invocation.method(
            #removeMedicalCondition,
            [
              uid,
              condition,
            ],
          ),
        )),
      ) as _i4.Future<_i2.FirestoreResult<void>>);

  @override
  _i4.Future<_i2.FirestoreResult<void>> addAllergy(
    String? uid,
    String? allergy,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAllergy,
          [
            uid,
            allergy,
          ],
        ),
        returnValue: _i4.Future<_i2.FirestoreResult<void>>.value(
            _FakeFirestoreResult_0<void>(
          this,
          Invocation.method(
            #addAllergy,
            [
              uid,
              allergy,
            ],
          ),
        )),
      ) as _i4.Future<_i2.FirestoreResult<void>>);

  @override
  _i4.Future<_i2.FirestoreResult<void>> removeAllergy(
    String? uid,
    String? allergy,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeAllergy,
          [
            uid,
            allergy,
          ],
        ),
        returnValue: _i4.Future<_i2.FirestoreResult<void>>.value(
            _FakeFirestoreResult_0<void>(
          this,
          Invocation.method(
            #removeAllergy,
            [
              uid,
              allergy,
            ],
          ),
        )),
      ) as _i4.Future<_i2.FirestoreResult<void>>);

  @override
  _i4.Future<_i2.FirestoreResult<void>> updateDietaryPreferences({
    required String? uid,
    required List<String>? dietaryNeeds,
    required List<String>? foodDislikes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDietaryPreferences,
          [],
          {
            #uid: uid,
            #dietaryNeeds: dietaryNeeds,
            #foodDislikes: foodDislikes,
          },
        ),
        returnValue: _i4.Future<_i2.FirestoreResult<void>>.value(
            _FakeFirestoreResult_0<void>(
          this,
          Invocation.method(
            #updateDietaryPreferences,
            [],
            {
              #uid: uid,
              #dietaryNeeds: dietaryNeeds,
              #foodDislikes: foodDislikes,
            },
          ),
        )),
      ) as _i4.Future<_i2.FirestoreResult<void>>);

  @override
  _i4.Future<_i2.FirestoreResult<void>> updateHealthGoals(
    String? uid,
    List<String>? healthGoals,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateHealthGoals,
          [
            uid,
            healthGoals,
          ],
        ),
        returnValue: _i4.Future<_i2.FirestoreResult<void>>.value(
            _FakeFirestoreResult_0<void>(
          this,
          Invocation.method(
            #updateHealthGoals,
            [
              uid,
              healthGoals,
            ],
          ),
        )),
      ) as _i4.Future<_i2.FirestoreResult<void>>);

  @override
  _i4.Future<_i2.FirestoreResult<void>> updateCulturalPreferences({
    required String? uid,
    required Map<String, dynamic>? culturalPreferences,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCulturalPreferences,
          [],
          {
            #uid: uid,
            #culturalPreferences: culturalPreferences,
          },
        ),
        returnValue: _i4.Future<_i2.FirestoreResult<void>>.value(
            _FakeFirestoreResult_0<void>(
          this,
          Invocation.method(
            #updateCulturalPreferences,
            [],
            {
              #uid: uid,
              #culturalPreferences: culturalPreferences,
            },
          ),
        )),
      ) as _i4.Future<_i2.FirestoreResult<void>>);

  @override
  _i4.Future<_i2.FirestoreResult<void>> updatePhysicalMeasurements({
    required String? uid,
    int? age,
    String? gender,
    double? height,
    double? weight,
    String? activityLevel,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePhysicalMeasurements,
          [],
          {
            #uid: uid,
            #age: age,
            #gender: gender,
            #height: height,
            #weight: weight,
            #activityLevel: activityLevel,
          },
        ),
        returnValue: _i4.Future<_i2.FirestoreResult<void>>.value(
            _FakeFirestoreResult_0<void>(
          this,
          Invocation.method(
            #updatePhysicalMeasurements,
            [],
            {
              #uid: uid,
              #age: age,
              #gender: gender,
              #height: height,
              #weight: weight,
              #activityLevel: activityLevel,
            },
          ),
        )),
      ) as _i4.Future<_i2.FirestoreResult<void>>);

  @override
  _i4.Future<_i2.FirestoreResult<List<_i2.UserModel>>> getSimilarUsers(
    String? uid, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSimilarUsers,
          [uid],
          {#limit: limit},
        ),
        returnValue: _i4.Future<_i2.FirestoreResult<List<_i2.UserModel>>>.value(
            _FakeFirestoreResult_0<List<_i2.UserModel>>(
          this,
          Invocation.method(
            #getSimilarUsers,
            [uid],
            {#limit: limit},
          ),
        )),
      ) as _i4.Future<_i2.FirestoreResult<List<_i2.UserModel>>>);

  @override
  _i4.Future<_i2.FirestoreResult<Map<String, bool>>>
      validateProfileCompleteness(String? uid) => (super.noSuchMethod(
            Invocation.method(
              #validateProfileCompleteness,
              [uid],
            ),
            returnValue:
                _i4.Future<_i2.FirestoreResult<Map<String, bool>>>.value(
                    _FakeFirestoreResult_0<Map<String, bool>>(
              this,
              Invocation.method(
                #validateProfileCompleteness,
                [uid],
              ),
            )),
          ) as _i4.Future<_i2.FirestoreResult<Map<String, bool>>>);

  @override
  _i4.Future<_i2.FirestoreResult<double>> getProfileCompletionPercentage(
          String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfileCompletionPercentage,
          [uid],
        ),
        returnValue: _i4.Future<_i2.FirestoreResult<double>>.value(
            _FakeFirestoreResult_0<double>(
          this,
          Invocation.method(
            #getProfileCompletionPercentage,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.FirestoreResult<double>>);
}
